#!/usr/bin/env sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
README="$ROOT_DIR/README.md"
MAKEFILE="$ROOT_DIR/Makefile"
GITIGNORE="$ROOT_DIR/.gitignore"
VALIDATOR="$ROOT_DIR/scripts/validate-openapi.rb"
GENERATOR="$ROOT_DIR/scripts/generate-spec-md.rb"
DOCS_PLANS="$ROOT_DIR/docs/plans"
PATH_ITEM_PLAN="$DOCS_PLANS/2026-06-13-path-item-metadata-validation.md"
GENERATED_MARKDOWN_PLAN="$DOCS_PLANS/2026-06-13-generated-markdown-spec.md"
CYCLIC_ALIAS_PLAN="$DOCS_PLANS/2026-06-15-cyclic-yaml-alias-validation.md"
PARSER_RECURSION_PLAN="$DOCS_PLANS/2026-06-15-yaml-parser-recursion-guard.md"
GENERATOR_RECURSION_PLAN="$DOCS_PLANS/2026-06-15-yaml-generator-recursion-guard.md"
GRAPH_WALKER_PLAN="$DOCS_PLANS/2026-06-16-yaml-graph-walker-depth.md"
DOCUMENT_ROOT_PLAN="$DOCS_PLANS/2026-06-17-yaml-document-root-validation.md"
CONTAINER_SHAPE_PLAN="$DOCS_PLANS/2026-06-17-openapi-container-shape-validation.md"
LOCATION_INDEPENDENT_MAKE_PLAN="$DOCS_PLANS/2026-06-14-location-independent-make.md"
WORKFLOW="$ROOT_DIR/.github/workflows/check.yml"

require_file() {
  path=$1
  if [ ! -f "$ROOT_DIR/$path" ]; then
    printf '%s\n' "Required file is missing: $path" >&2
    exit 1
  fi
}

for path in \
  "AGENTS.md" \
  ".gitignore" \
  "CHANGES.md" \
  "Makefile" \
  "README.md" \
  "SECURITY.md" \
  "VISION.md" \
  "spec.md" \
  "spec.yaml" \
  "scripts/generate-spec-md.rb" \
  "scripts/test-generator.sh" \
  "scripts/test-validator.sh" \
  "scripts/validate-openapi.rb" \
  "docs/plans/2026-06-08-placeholder-server-validation.md" \
  "docs/plans/2026-06-09-scripted-baseline-check.md" \
  "docs/plans/2026-06-10-hosted-openapi-validation.md" \
  "docs/plans/2026-06-10-local-reference-validation.md" \
  "docs/plans/2026-06-12-credential-free-openapi-validation.md" \
  "docs/plans/2026-06-12-response-description-validation.md" \
  "docs/plans/2026-06-12-self-contained-reference-validation.md" \
  "docs/plans/2026-06-13-operation-id-validation.md" \
  "docs/plans/2026-06-13-path-item-metadata-validation.md" \
  "docs/plans/2026-06-13-generated-markdown-spec.md" \
  "docs/plans/2026-06-15-cyclic-yaml-alias-validation.md" \
  "docs/plans/2026-06-15-yaml-parser-recursion-guard.md" \
  "docs/plans/2026-06-15-yaml-generator-recursion-guard.md" \
  "docs/plans/2026-06-16-yaml-graph-walker-depth.md" \
  "docs/plans/2026-06-17-yaml-document-root-validation.md" \
  "docs/plans/2026-06-17-openapi-container-shape-validation.md" \
  "docs/plans/2026-06-14-location-independent-make.md" \
  ".github/workflows/check.yml" \
  "scripts/check-baseline.sh"; do
  require_file "$path"
done

if ! [ -x "$VALIDATOR" ]; then
  printf '%s\n' "scripts/validate-openapi.rb must be executable." >&2
  exit 1
fi

if ! [ -x "$GENERATOR" ]; then
  printf '%s\n' "scripts/generate-spec-md.rb must be executable." >&2
  exit 1
fi

if ! [ -x "$ROOT_DIR/scripts/test-generator.sh" ]; then
  printf '%s\n' "scripts/test-generator.sh must be executable." >&2
  exit 1
fi

if ! [ -x "$ROOT_DIR/scripts/test-validator.sh" ]; then
  printf '%s\n' "scripts/test-validator.sh must be executable." >&2
  exit 1
fi

for target in "generate:" "lint:" "test:" "build:" "verify:" "check:"; do
  if ! grep -Fq "$target" "$MAKEFILE"; then
    printf '%s\n' "Makefile must expose the $target gate." >&2
    exit 1
  fi
done

for make_contract in \
  'override REPO_ROOT := $(abspath $(dir $(lastword $(MAKEFILE_LIST))))' \
  'generate: $(REPO_ROOT)/scripts/generate-spec-md.rb $(REPO_ROOT)/spec.yaml' \
  'cd "$(REPO_ROOT)" && scripts/check-baseline.sh' \
  'cd "$(REPO_ROOT)" && scripts/generate-spec-md.rb' \
  'cd "$(REPO_ROOT)" && scripts/validate-openapi.rb' \
  'cd "$(REPO_ROOT)" && scripts/test-validator.sh' \
  'cd "$(REPO_ROOT)" && scripts/test-generator.sh'; do
  if ! grep -Fq "$make_contract" "$MAKEFILE"; then
    printf '%s\n' "Makefile must remain caller-directory independent: $make_contract" >&2
    exit 1
  fi
done

for evidence in \
  '## Status Completed' \
  'Ruby 2.7.0' \
  'Ruby 3.3' \
  'absolute Makefile path from /tmp' \
  'REPO_ROOT=/tmp' \
  'byte-identical' \
  'seven isolated hostile mutations' \
  'git diff --check' \
  'credential-pattern'; do
  if ! grep -Fq "$evidence" "$LOCATION_INDEPENDENT_MAKE_PLAN"; then
    printf '%s\n' "Location-independent Make plan must preserve evidence: $evidence" >&2
    exit 1
  fi
done

for document in "$README" "$ROOT_DIR/SECURITY.md" "$ROOT_DIR/VISION.md" "$ROOT_DIR/CHANGES.md"; do
  if ! grep -Fqi "generat" "$document" || ! grep -Fq "spec.yaml" "$document"; then
    printf '%s\n' "$document must document generated Markdown from spec.yaml." >&2
    exit 1
  fi
done

for generator_contract in \
  "usage: scripts/generate-spec-md.rb [--check]" \
  "spec.md is out of date; run scripts/generate-spec-md.rb" \
  "Generated by scripts/generate-spec-md.rb from spec.yaml" \
  "File.read(REFERENCE_PATH) == generated"; do
  if ! grep -Fq "$generator_contract" "$GENERATOR"; then
    printf '%s\n' "Markdown generator must preserve: $generator_contract" >&2
    exit 1
  fi
done

for generator_test_contract in \
  "generator check accepted stale Markdown" \
  "Mutation operation summary" \
  "Mutation field description" \
  "Mutation response description" \
  "Mutation security description" \
  "Mutation error example" \
  "generator accepted an unsupported argument"; do
  if ! grep -Fq "$generator_test_contract" "$ROOT_DIR/scripts/test-generator.sh"; then
    printf '%s\n' "Generator mutation tests must preserve: $generator_test_contract" >&2
    exit 1
  fi
done

for validator_generation_contract in \
  "docs/plans/2026-06-13-generated-markdown-spec.md" \
  "scripts/generate-spec-md.rb" \
  "spec.md must match scripts/generate-spec-md.rb output"; do
  if ! grep -Fq "$validator_generation_contract" "$VALIDATOR"; then
    printf '%s\n' "OpenAPI validator must preserve generation contract: $validator_generation_contract" >&2
    exit 1
  fi
done

if ! grep -Fq 'Ruby and `make`' "$README"; then
  printf '%s\n' 'README must document Ruby and `make`.' >&2
  exit 1
fi

for documented in \
  "make check" \
  "make build" \
  "scripts/check-baseline.sh" \
  'Every OpenAPI `$ref` must be a local string' \
  "Every OpenAPI response must include a non-empty"; do
  if ! grep -Fq "$documented" "$README"; then
    printf '%s\n' "README must document $documented." >&2
    exit 1
  fi
done

if ! grep -Fq "docs/plans/2026-06-09-scripted-baseline-check.md" "$VALIDATOR"; then
  printf '%s\n' "OpenAPI validator must include the scripted baseline plan." >&2
  exit 1
fi

if ! grep -Fq "docs/plans/2026-06-12-self-contained-reference-validation.md" "$VALIDATOR"; then
  printf '%s\n' "OpenAPI validator must include the self-contained reference plan." >&2
  exit 1
fi

for validator_contract in \
  "HTTP_METHODS = %w[get put post delete options head patch trace]" \
  "PATH_ITEM_FIELDS" \
  "next unless HTTP_METHODS.include?(method.to_s)" \
  "unless path_item.is_a?(Hash)" \
  "unless operation.is_a?(Hash)" \
  "path item #{path} must be an object" \
  "contains unsupported field" \
  "operation must be an object" \
  "operationId must be a non-empty string" \
  "duplicate operationId values" \
  "response missing description" \
  "def resolve_json_pointer" \
  "contains non-local reference" \
  '$ref must be a string' \
  "validate_references(spec, spec"; do
  if ! grep -Fq "$validator_contract" "$VALIDATOR"; then
    printf '%s\n' "OpenAPI validator must preserve: $validator_contract" >&2
    exit 1
  fi
done

for cycle_contract in \
  'def cyclic_object_graph?' \
  'stack = [[:enter, root]]' \
  'action, node = stack.pop' \
  'return true if visiting[object_id]' \
  'next if visited[object_id]' \
  'stack << [:exit, node]' \
  'stack << [:enter, value]' \
  'stack << [:enter, key]' \
  'visiting.delete(object_id)' \
  'visited[object_id] = true' \
  'if cyclic_object_graph?(spec)' \
  'spec.yaml contains cyclic YAML aliases'; do
  if ! grep -Fq "$cycle_contract" "$VALIDATOR"; then
    printf '%s\n' "OpenAPI validator must preserve cyclic-alias protection: $cycle_contract" >&2
    exit 1
  fi
done

cycle_check_line=$(grep -nF 'if cyclic_object_graph?(spec)' "$VALIDATOR" | cut -d: -f1)
generator_line=$(grep -nF "generator = File.join(ROOT_DIR, 'scripts/generate-spec-md.rb')" "$VALIDATOR" | cut -d: -f1)
if [ -z "$cycle_check_line" ] || [ -z "$generator_line" ] || [ "$cycle_check_line" -ge "$generator_line" ]; then
  printf '%s\n' 'OpenAPI validator must reject cyclic aliases before generator execution.' >&2
  exit 1
fi

cycle_assertion=$(sed -n '/^assert_cycle_rejected() {/,/^}/p' "$ROOT_DIR/scripts/test-validator.sh")
for executable_assertion in \
  '  if output=$(GENERATOR_CALL_LOG="$call_log" ruby -rtimeout -e \' \
  "    'Timeout.timeout(5) { load ARGV.fetch(0) }' \\" \
  '  if [ "$output" != "spec.yaml contains cyclic YAML aliases" ]; then' \
  '  if [ -e "$call_log" ]; then'; do
  if ! printf '%s\n' "$cycle_assertion" | grep -Fqx "$executable_assertion"; then
    printf '%s\n' "Cycle assertion must preserve executable line: $executable_assertion" >&2
    exit 1
  fi
done
if printf '%s\n' "$cycle_assertion" | grep -Eq '^[[:space:]]*return([[:space:]]|$)'; then
  printf '%s\n' 'Cycle assertion must not bypass its executable checks.' >&2
  exit 1
fi

for cycle_scenario in \
  'cyclic YAML alias' \
  'cyclic YAML mapping key' \
  'cyclic YAML array alias' \
  'deep cyclic YAML alias chain'; do
  if [ "$(grep -Ec "^[[:space:]]*assert_cycle_rejected \"$cycle_scenario\"[[:space:]]*$" "$ROOT_DIR/scripts/test-validator.sh")" -ne 1 ]; then
    printf '%s\n' "Validator mutation tests must execute exactly one scenario: $cycle_scenario" >&2
    exit 1
  fi
done

for mutation_contract in \
  'spec.yaml contains cyclic YAML aliases' \
  'The generator must not run for cyclic aliases' \
  'Validator rejected an acyclic shared YAML alias'; do
  if ! grep -Fq "$mutation_contract" "$ROOT_DIR/scripts/test-validator.sh"; then
    printf '%s\n' "Validator mutation tests must preserve cyclic-alias coverage: $mutation_contract" >&2
    exit 1
  fi
done

for plan_contract in \
  '## Status' \
  'Completed' \
  '## Verification Completed' \
  'Ruby 2.7.0' \
  'Ruby 3.3.11' \
  'absolute-Makefile `make check`' \
  'Fifteen isolated hostile mutations were rejected' \
  'git diff --check' \
  'credential-pattern' \
  'spec.yaml` and `spec.md` remained byte-identical'; do
  if ! grep -Fq "$plan_contract" "$CYCLIC_ALIAS_PLAN"; then
    printf '%s\n' "Cyclic-alias plan must preserve completed evidence: $plan_contract" >&2
    exit 1
  fi
done
if grep -Eiq 'pending|in[[:space:]]+progress|remain(s|ed)?[[:space:]]+(unfinished|to[[:space:]]+be)' "$CYCLIC_ALIAS_PLAN"; then
  printf '%s\n' 'Cyclic-alias plan must not retain provisional verification language.' >&2
  exit 1
fi

parser_load_block=$(sed -n '/^begin$/,/^end$/p' "$VALIDATOR")
if ! grep -Fqx "spec_source = File.read('spec.yaml')" "$VALIDATOR"; then
  printf '%s\n' 'YAML parser recursion guard must read spec.yaml outside the rescue boundary.' >&2
  exit 1
fi
for executable_contract in \
  '  spec = YAML.safe_load(spec_source, aliases: true)' \
  'rescue SystemStackError' \
  "  warn 'spec.yaml exceeds the YAML parser nesting limit'" \
  '  exit 1'; do
  if ! printf '%s\n' "$parser_load_block" | grep -Fqx "$executable_contract"; then
    printf '%s\n' "YAML parser recursion guard must preserve executable line: $executable_contract" >&2
    exit 1
  fi
done
if printf '%s\n' "$parser_load_block" | grep -Eq '^rescue([[:space:]]*$|[[:space:]]+(Exception|NoMemoryError|ScriptError))'; then
  printf '%s\n' 'YAML parser recursion guard must not broaden beyond SystemStackError.' >&2
  exit 1
fi

parser_assertion=$(sed -n '/^assert_parser_recursion_rejected() {/,/^}/p' "$ROOT_DIR/scripts/test-validator.sh")
for executable_contract in \
  '  if output=$(GENERATOR_CALL_LOG="$call_log" ruby -rtimeout -e \' \
  "    'Timeout.timeout(5) { load ARGV.fetch(0) }' \\" \
  '  if [ "$output" != "spec.yaml exceeds the YAML parser nesting limit" ]; then' \
  '  if [ -e "$call_log" ]; then'; do
  if ! printf '%s\n' "$parser_assertion" | grep -Fqx "$executable_contract"; then
    printf '%s\n' "Parser recursion assertion must preserve executable line: $executable_contract" >&2
    exit 1
  fi
done
if printf '%s\n' "$parser_assertion" | grep -Eq '^[[:space:]]*return([[:space:]]|$)'; then
  printf '%s\n' 'Parser recursion assertion must not bypass its executable checks.' >&2
  exit 1
fi
if [ "$(grep -Ec '^[[:space:]]*assert_parser_recursion_rejected[[:space:]]*$' "$ROOT_DIR/scripts/test-validator.sh")" -ne 1 ]; then
  printf '%s\n' 'Validator tests must execute exactly one parser recursion scenario.' >&2
  exit 1
fi
for fixture_contract in \
  '1.upto(2_000)' \
  'Validator rejected a shallow acyclic YAML mapping.' \
  "*'Psych::SyntaxError'*)" \
  'Malformed YAML was mislabeled as parser recursion.'; do
  if ! grep -Fq "$fixture_contract" "$ROOT_DIR/scripts/test-validator.sh"; then
    printf '%s\n' "Parser recursion tests must preserve: $fixture_contract" >&2
    exit 1
  fi
done
if ! grep -Fq "'docs/plans/2026-06-15-yaml-parser-recursion-guard.md'" "$VALIDATOR"; then
  printf '%s\n' 'OpenAPI validator must register the YAML parser recursion plan.' >&2
  exit 1
fi

for plan_contract in \
  '## Status' \
  'Completed' \
  '## Verification Completed' \
  'Ruby 2.7.0' \
  'Ruby 3.3.11' \
  'absolute-Makefile `make check`' \
  'isolated hostile mutations were rejected' \
  'git diff --check' \
  'credential-pattern' \
  'spec.yaml` and `spec.md` remained byte-identical'; do
  if ! grep -Fq "$plan_contract" "$PARSER_RECURSION_PLAN"; then
    printf '%s\n' "Parser recursion plan must preserve completed evidence: $plan_contract" >&2
    exit 1
  fi
done
if grep -Eiq 'pending|in[[:space:]]+progress|remain(s|ed)?[[:space:]]+(unfinished|to[[:space:]]+be)' "$PARSER_RECURSION_PLAN"; then
  printf '%s\n' 'Parser recursion plan must not retain provisional verification language.' >&2
  exit 1
fi

generator_parse_block=$(sed -n '/^spec_source = File.read/,/^generated = generate_reference/p' "$GENERATOR")
for generator_contract in \
  'spec_source = File.read(SPEC_PATH)' \
  'spec = YAML.safe_load(spec_source, aliases: true)' \
  'rescue SystemStackError' \
  "warn 'spec.yaml exceeds the YAML generator parser nesting limit'" \
  'generated = generate_reference(spec)'; do
  if ! printf '%s\n' "$generator_parse_block" | grep -Fq "$generator_contract"; then
    printf '%s\n' "YAML generator recursion guard must preserve: $generator_contract" >&2
    exit 1
  fi
done
if printf '%s\n' "$generator_parse_block" | grep -Eq 'rescue (StandardError|Exception)'; then
  printf '%s\n' 'YAML generator recursion guard must not broaden beyond SystemStackError.' >&2
  exit 1
fi
for fixture_contract in \
  'generator accepted YAML beyond the parser nesting limit' \
  'generator returned the wrong parser recursion error:' \
  'spec.yaml exceeds the YAML generator parser nesting limit' \
  'cmp "$WORK_DIR/spec.md.before-recursion" "$WORK_DIR/spec.md"'; do
  if ! grep -Fq "$fixture_contract" "$ROOT_DIR/scripts/test-generator.sh"; then
    printf '%s\n' "Generator recursion tests must preserve: $fixture_contract" >&2
    exit 1
  fi
done
for plan_contract in \
  'status: completed' \
  '## Work Completed' \
  '## Verification Completed' \
  'All four Make gates passed' \
  'external directory' \
  'Six isolated hostile mutations were rejected'; do
  if ! grep -Fq "$plan_contract" "$GENERATOR_RECURSION_PLAN"; then
    printf '%s\n' "Generator recursion plan must preserve completed evidence: $plan_contract" >&2
    exit 1
  fi
done
if grep -Eiq 'pending|in[[:space:]]+progress|remain(s|ed)?[[:space:]]+(unfinished|to[[:space:]]+be)' "$GENERATOR_RECURSION_PLAN"; then
  printf '%s\n' 'Generator recursion plan must not retain provisional verification language.' >&2
  exit 1
fi

for graph_walker_contract in \
  'def each_graph_node(root, root_path)' \
  'stack = [[root, root_path]]' \
  'node, path = stack.pop' \
  'next if visited[node.object_id]' \
  'visited[node.object_id] = true' \
  'node.reverse_each do |key, value|' \
  '(node.length - 1).downto(0) do |index|' \
  'each_graph_node(root, root_path) do |node, path|'; do
  if ! grep -Fq "$graph_walker_contract" "$VALIDATOR"; then
    printf '%s\n' "YAML graph walkers must preserve: $graph_walker_contract" >&2
    exit 1
  fi
done
if [ "$(grep -Fc 'each_graph_node(root, root_path) do |node, path|' "$VALIDATOR")" -ne 3 ]; then
  printf '%s\n' 'All three whole-document validators must use the bounded graph walker.' >&2
  exit 1
fi
for fixture_contract in \
  '1.upto(5_000) do |index|' \
  "Timeout.timeout(10) { load ARGV.fetch(0) }" \
  'Validator rejected a deep acyclic YAML alias graph:' \
  'Deep acyclic YAML alias graph exhausted the validator stack:'; do
  if ! grep -Fq "$fixture_contract" "$ROOT_DIR/scripts/test-validator.sh"; then
    printf '%s\n' "YAML graph walker tests must preserve: $fixture_contract" >&2
    exit 1
  fi
done
if ! grep -Fq "'docs/plans/2026-06-16-yaml-graph-walker-depth.md'" "$VALIDATOR"; then
  printf '%s\n' 'OpenAPI validator must register the YAML graph walker plan.' >&2
  exit 1
fi
for plan_contract in \
  '## Status Completed' \
  '## Verification Completed' \
  'Ruby 2.7.0' \
  'Ruby 3.3' \
  'external-directory `make check`' \
  'isolated hostile mutations were rejected' \
  'git diff --check' \
  'credential-pattern' \
  'spec.yaml` and `spec.md` remained byte-identical'; do
  if ! grep -Fq "$plan_contract" "$GRAPH_WALKER_PLAN"; then
    printf '%s\n' "YAML graph walker plan must preserve completed evidence: $plan_contract" >&2
    exit 1
  fi
done
if grep -Eiq 'pending|in[[:space:]]+progress|remain(s|ed)?[[:space:]]+(unfinished|to[[:space:]]+be)' "$GRAPH_WALKER_PLAN"; then
  printf '%s\n' 'YAML graph walker plan must not retain provisional verification language.' >&2
  exit 1
fi

for root_guard_contract in \
  'unless spec.is_a?(Hash)' \
  'spec.yaml root must be a mapping for OpenAPI validation'; do
  if ! grep -Fq "$root_guard_contract" "$VALIDATOR"; then
    printf '%s\n' "OpenAPI validator must preserve the document-root guard: $root_guard_contract" >&2
    exit 1
  fi
done
for root_guard_contract in \
  'unless spec.is_a?(Hash)' \
  'spec.yaml root must be a mapping for Markdown generation'; do
  if ! grep -Fq "$root_guard_contract" "$GENERATOR"; then
    printf '%s\n' "OpenAPI generator must preserve the document-root guard: $root_guard_contract" >&2
    exit 1
  fi
done
validator_root_line=$(grep -nF 'unless spec.is_a?(Hash)' "$VALIDATOR" | cut -d: -f1)
validator_cycle_line=$(grep -nF 'if cyclic_object_graph?(spec)' "$VALIDATOR" | cut -d: -f1)
validator_generator_line=$(grep -nF "unless File.file?(generator) && system(generator, '--check'" "$VALIDATOR" | cut -d: -f1)
if [ -z "$validator_root_line" ] || [ -z "$validator_cycle_line" ] || [ -z "$validator_generator_line" ] ||
   [ "$validator_root_line" -ge "$validator_cycle_line" ] || [ "$validator_root_line" -ge "$validator_generator_line" ]; then
  printf '%s\n' 'OpenAPI validator must reject non-mapping roots before graph traversal or generator invocation.' >&2
  exit 1
fi
generator_root_line=$(grep -nF 'unless spec.is_a?(Hash)' "$GENERATOR" | cut -d: -f1)
generator_render_line=$(grep -nF 'generated = generate_reference(spec)' "$GENERATOR" | cut -d: -f1)
if [ -z "$generator_root_line" ] || [ -z "$generator_render_line" ] || [ "$generator_root_line" -ge "$generator_render_line" ]; then
  printf '%s\n' 'OpenAPI generator must reject non-mapping roots before rendering.' >&2
  exit 1
fi
for fixture_contract in \
  'assert_document_root_rejected "empty"' \
  'assert_document_root_rejected "scalar"' \
  'assert_document_root_rejected "sequence"'; do
  if ! grep -Fq "$fixture_contract" "$ROOT_DIR/scripts/test-validator.sh" ||
     ! grep -Fq "$fixture_contract" "$ROOT_DIR/scripts/test-generator.sh"; then
    printf '%s\n' "Document-root tests must preserve both entry-point fixtures: $fixture_contract" >&2
    exit 1
  fi
done
for fixture_contract in \
  'The generator must not run for a $label YAML document root.' \
  'cmp "$ROOT_DIR/spec.md" "$WORK_DIR/spec.md"'; do
  if ! grep -Fq "$fixture_contract" "$ROOT_DIR/scripts/test-validator.sh" &&
     ! grep -Fq "$fixture_contract" "$ROOT_DIR/scripts/test-generator.sh"; then
    printf '%s\n' "Document-root tests must preserve rejection side effects: $fixture_contract" >&2
    exit 1
  fi
done
if ! grep -Fq "'docs/plans/2026-06-17-yaml-document-root-validation.md'" "$VALIDATOR"; then
  printf '%s\n' 'OpenAPI validator must register the YAML document-root plan.' >&2
  exit 1
fi
for plan_contract in \
  '## Status Completed' \
  '## Work Completed' \
  '## Verification Completed' \
  'make check' \
  'hostile mutations' \
  'spec.yaml` and `spec.md` remained byte-identical'; do
  if ! grep -Fq "$plan_contract" "$DOCUMENT_ROOT_PLAN"; then
    printf '%s\n' "YAML document-root plan must preserve completed evidence: $plan_contract" >&2
    exit 1
  fi
done
if grep -Eiq 'pending|in[[:space:]]+progress|remain(s|ed)?[[:space:]]+(unfinished|to[[:space:]]+be)' "$DOCUMENT_ROOT_PLAN"; then
  printf '%s\n' 'YAML document-root plan must not retain provisional verification language.' >&2
  exit 1
fi

validator_shape_line=$(grep -nF 'if (shape_error = openapi_container_shape_error(spec))' "$VALIDATOR" | cut -d: -f1)
if [ -z "$validator_shape_line" ] || [ "$validator_cycle_line" -ge "$validator_shape_line" ] ||
   [ "$validator_shape_line" -ge "$validator_generator_line" ]; then
  printf '%s\n' 'OpenAPI validator must reject malformed container shapes after cycle validation and before generator invocation.' >&2
  exit 1
fi
generator_shape_line=$(grep -nF 'if (shape_error = openapi_container_shape_error(spec))' "$GENERATOR" | cut -d: -f1)
if [ -z "$generator_shape_line" ] || [ "$generator_root_line" -ge "$generator_shape_line" ] ||
   [ "$generator_shape_line" -ge "$generator_render_line" ]; then
  printf '%s\n' 'OpenAPI generator must reject malformed container shapes before rendering.' >&2
  exit 1
fi
for shape_contract in \
  'spec.yaml info must be a mapping' \
  'spec.yaml paths must be a mapping' \
  'spec.yaml components must be a mapping' \
  'spec.yaml components.schemas must be a mapping' \
  'spec.yaml components.securitySchemes must be a mapping' \
  'spec.yaml servers must be an array'; do
  if ! grep -Fq "$shape_contract" "$VALIDATOR" || ! grep -Fq "$shape_contract" "$GENERATOR"; then
    printf '%s\n' "Both OpenAPI entry points must preserve container-shape diagnostics: $shape_contract" >&2
    exit 1
  fi
done
for fixture_contract in \
  'assert_container_shape_rejected info' \
  'assert_container_shape_rejected paths' \
  'assert_container_shape_rejected components.schemas' \
  'assert_container_shape_rejected components.securitySchemes' \
  'assert_container_shape_rejected servers'; do
  if ! grep -Fq "$fixture_contract" "$ROOT_DIR/scripts/test-validator.sh" ||
     ! grep -Fq "$fixture_contract" "$ROOT_DIR/scripts/test-generator.sh"; then
    printf '%s\n' "Container-shape tests must preserve both entry-point fixtures: $fixture_contract" >&2
    exit 1
  fi
done
for side_effect_contract in \
  'The generator must not run for malformed $label.' \
  'cmp "$ROOT_DIR/spec.md" "$WORK_DIR/spec.md"'; do
  if ! grep -Fq "$side_effect_contract" "$ROOT_DIR/scripts/test-validator.sh" &&
     ! grep -Fq "$side_effect_contract" "$ROOT_DIR/scripts/test-generator.sh"; then
    printf '%s\n' "Container-shape tests must preserve rejection side effects: $side_effect_contract" >&2
    exit 1
  fi
done
if ! grep -Fq "'docs/plans/2026-06-17-openapi-container-shape-validation.md'" "$VALIDATOR"; then
  printf '%s\n' 'OpenAPI validator must register the container-shape plan.' >&2
  exit 1
fi
for plan_contract in \
  '## Status Completed' \
  '## Work Completed' \
  '## Verification Completed' \
  'make check' \
  'hostile mutations' \
  'spec.yaml` and generated `spec.md` remained byte-identical'; do
  if ! grep -Fq "$plan_contract" "$CONTAINER_SHAPE_PLAN"; then
    printf '%s\n' "Container-shape plan must preserve completed evidence: $plan_contract" >&2
    exit 1
  fi
done
if grep -Eiq 'pending|in[[:space:]]+progress|remain(s|ed)?[[:space:]]+(unfinished|to[[:space:]]+be)' "$CONTAINER_SHAPE_PLAN"; then
  printf '%s\n' 'Container-shape plan must not retain provisional verification language.' >&2
  exit 1
fi

for document in "$README" "$ROOT_DIR/SECURITY.md" "$ROOT_DIR/VISION.md" "$ROOT_DIR/CHANGES.md"; do
  if ! grep -Fqi 'top-level container shapes' "$document"; then
    printf '%s\n' "$document must document top-level container shapes." >&2
    exit 1
  fi
done

for document in "$README" "$ROOT_DIR/SECURITY.md" "$ROOT_DIR/VISION.md" "$ROOT_DIR/CHANGES.md"; do
  if ! grep -Fqi 'generator parser recursion failures' "$document"; then
    printf '%s\n' "$document must document generator parser recursion failures." >&2
    exit 1
  fi
done

for document in "$README" "$ROOT_DIR/SECURITY.md" "$ROOT_DIR/VISION.md" "$ROOT_DIR/CHANGES.md"; do
  if ! grep -Fq "Path Item metadata" "$document"; then
    printf '%s\n' "$document must document Path Item metadata validation." >&2
    exit 1
  fi
done

for evidence in \
  "## Status" \
  "Completed" \
  "Ruby 2.7" \
  "Ruby 3.3" \
  "make check" \
  "hostile mutations rejected" \
  "git diff --check" \
  "secret, captured-prompt, generated-artifact, specification, and dependency scan"; do
  if ! grep -Fq "$evidence" "$PATH_ITEM_PLAN"; then
    printf '%s\n' "Path Item validation plan must preserve completed evidence: $evidence" >&2
    exit 1
  fi
done

for evidence in \
  "## Status" \
  "Completed" \
  "Ruby 2.7" \
  "Ruby 3.3" \
  "make check" \
  "hostile mutations rejected" \
  "git diff --check" \
  "secret, captured-prompt, generated-artifact, specification, and dependency scan"; do
  if ! grep -Fq "$evidence" "$GENERATED_MARKDOWN_PLAN"; then
    printf '%s\n' "Generated Markdown plan must preserve completed evidence: $evidence" >&2
    exit 1
  fi
done

for mutation_contract in \
  "standard Path Item metadata" \
  "unsupported Path Item field" \
  "non-object Path Item" \
  "non-object operation" \
  "missing operation ID" \
  "whitespace-only operation ID" \
  "non-string operation ID" \
  "duplicate operation ID" \
  "whitespace-only response description" \
  "dangling local reference" \
  "external URL reference" \
  "relative file reference" \
  "malformed local reference" \
  "non-string reference" \
  "Escaped~1Schema~0Name"; do
  if ! grep -Fq "$mutation_contract" "$ROOT_DIR/scripts/test-validator.sh"; then
    printf '%s\n' "Validator mutation tests must preserve: $mutation_contract" >&2
    exit 1
  fi
done

if ! grep -Fq "docs/plans/2026-06-10-hosted-openapi-validation.md" "$VALIDATOR"; then
  printf '%s\n' "OpenAPI validator must include the hosted validation plan." >&2
  exit 1
fi

expected_workflow=$(cat <<'EOF'
name: Check

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: check-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  openapi:
    name: OpenAPI contract validation
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        ruby-version: ["2.7", "3.3"]
    steps:
      - name: Check out repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Set up Ruby
        uses: ruby/setup-ruby@89f90524b88a01fe6e0b732220432cc6142926af # v1.313.0
        with:
          ruby-version: ${{ matrix.ruby-version }}
      - name: Validate OpenAPI contract
        run: make check
EOF
)
actual_workflow=$(cat "$WORKFLOW")
if [ "$actual_workflow" != "$expected_workflow" ]; then
  printf '%s\n' "Hosted validation must match the exact pinned, credential-free OpenAPI contract." >&2
  exit 1
fi

for guardrail in "make check" "spec.yaml" "security scheme" "credential-adjacent"; do
  if ! grep -Fqi "$guardrail" "$ROOT_DIR/AGENTS.md"; then
    printf '%s\n' "AGENTS.md must preserve the guardrail: $guardrail" >&2
    exit 1
  fi
done

if ! (cd / && "$VALIDATOR" >/dev/null); then
  printf '%s\n' "OpenAPI validator must run independently of the caller's working directory." >&2
  exit 1
fi

for ignored in ".env" ".env.*" "*.log" ".idea/" ".vscode/" "*.iml" ".DS_Store"; do
  if ! grep -Fq "$ignored" "$GITIGNORE"; then
    printf '%s\n' ".gitignore must include $ignored" >&2
    exit 1
  fi
done

if ! tracked_local=$(git -C "$ROOT_DIR" ls-files '.env' '.env.*' '.idea' '.vscode' '*.iml'); then
  printf '%s\n' "Baseline must be able to inspect tracked secret and editor metadata paths." >&2
  exit 1
fi
if [ -n "$tracked_local" ]; then
  printf '%s\n%s\n' "Local secrets or editor metadata must not be tracked:" "$tracked_local" >&2
  exit 1
fi

found_plan=0
for plan in "$DOCS_PLANS"/*.md; do
  [ -e "$plan" ] || continue
  found_plan=1
  completed_statuses=$(awk '
    $0 == "## Status Completed" { count += 1; next }
    $0 == "## Status" { in_status = 1; next }
    in_status && /^## / { in_status = 0 }
    in_status && $0 == "Completed" { count += 1 }
    END { print count + 0 }
  ' "$plan")
  if [ "$completed_statuses" -ne 1 ]; then
    printf '%s\n' "$plan must record completed status." >&2
    exit 1
  fi
  if ! grep -Fq "make check" "$plan"; then
    printf '%s\n' "$plan must document make check verification." >&2
    exit 1
  fi
done

if [ "$found_plan" -eq 0 ]; then
  printf '%s\n' "docs/plans must contain completed markdown plans." >&2
  exit 1
fi
