#!/usr/bin/env ruby
# frozen_string_literal: true

require 'json'
require 'yaml'

ROOT_DIR = File.expand_path('..', __dir__)
SPEC_PATH = File.join(ROOT_DIR, 'spec.yaml')
REFERENCE_PATH = File.join(ROOT_DIR, 'spec.md')
HTTP_METHODS = %w[get put post delete options head patch trace].freeze

def normalized_text(value)
  value.to_s.lines.map(&:strip).reject(&:empty?).join(' ')
end

def schema_type(schema)
  return schema.fetch('$ref').split('/').last if schema.key?('$ref')

  type = schema.fetch('type', 'value').to_s
  return type unless type == 'array'

  "array of #{schema_type(schema.fetch('items', {}))}"
end

def render_default(value)
  value.is_a?(String) ? value : JSON.generate(value)
end

def request_schema(spec, operation)
  schema = operation.dig('requestBody', 'content', 'application/json', 'schema')
  return unless schema.is_a?(Hash)
  return schema unless schema['$ref']

  spec.dig('components', 'schemas', schema.fetch('$ref').split('/').last)
end

def error_example(schema)
  schema.fetch('properties', {}).each_with_object({}) do |(name, property), example|
    example[name] = property.fetch('example', property.fetch('type', 'value'))
  end
end

def generate_reference(spec)
  info = spec.fetch('info')
  lines = []
  title = info.fetch('title').to_s
  title = "#{title} API" unless title.end_with?('API')
  lines << "# #{title}"
  lines << ''
  lines << '<!-- Generated by scripts/generate-spec-md.rb from spec.yaml. Do not edit directly. -->'
  lines << ''
  lines << '## Overview'
  lines << ''
  lines << normalized_text(info['description'])
  lines << ''
  lines << '## API Information'
  lines << ''
  lines << "- **Version**: #{info.fetch('version')}"
  contact = info.fetch('contact', {})
  lines << "- **Contact**: [#{contact.fetch('name')}](#{contact.fetch('url')}) (#{contact.fetch('email')})"
  license = info.fetch('license', {})
  lines << "- **License**: [#{license.fetch('name')}](#{license.fetch('url')})"
  lines << ''
  lines << '## Servers'
  lines << ''
  Array(spec['servers']).each do |server|
    lines << "- **#{normalized_text(server['description'])}**: `#{server.fetch('url')}`"
  end
  lines << ''
  lines << '## Endpoints'

  operation_number = 0
  spec.fetch('paths').each do |path, path_item|
    path_item.each do |method, operation|
      next unless HTTP_METHODS.include?(method.to_s)

      operation_number += 1
      lines << ''
      lines << "### #{operation_number}. #{operation.fetch('summary')}"
      lines << ''
      lines << "- **Endpoint**: `#{path}`"
      lines << "- **Method**: `#{method.to_s.upcase}`"
      lines << "- **Operation ID**: `#{operation.fetch('operationId')}`"
      lines << "- **Description**: #{normalized_text(operation['description'])}"
      schema = request_schema(spec, operation)
      if schema
        required = Array(schema['required'])
        lines << '- **Request Body**:'
        schema.fetch('properties', {}).each do |name, property|
          requirement = required.include?(name) ? 'required' : 'optional'
          detail = normalized_text(property['description'])
          detail += " (default: `#{render_default(property['default'])}`)" if property.key?('default')
          lines << "  - `#{name}` (#{schema_type(property)}, #{requirement}): #{detail}"
        end
      end
      lines << ''
      lines << '- **Responses**:'
      operation.fetch('responses', {}).each do |status, response|
        lines << "  - `#{status}`: #{normalized_text(response['description'])}"
      end
    end
  end

  lines << ''
  lines << '## Security'
  lines << ''
  lines << 'The API uses the following authentication schemes:'
  lines << ''
  spec.dig('components', 'securitySchemes').each do |name, scheme|
    detail = case scheme.fetch('type')
             when 'apiKey'
               "API key in the #{scheme.fetch('in')} `#{scheme.fetch('name')}`"
             when 'http'
               "HTTP `#{scheme.fetch('scheme')}` authentication"
             else
               scheme.fetch('type').to_s
             end
    lines << "- **`#{name}`**: #{detail}. #{normalized_text(scheme['description'])}"
  end

  error_schema = spec.dig('components', 'schemas', 'Error')
  lines << ''
  lines << '## Error Handling'
  lines << ''
  lines << normalized_text(error_schema['description'])
  lines << ''
  lines << '```json'
  lines.concat(JSON.pretty_generate(error_example(error_schema)).lines.map(&:chomp))
  lines << '```'
  lines << ''
  lines << '## Conclusion'
  lines << ''
  lines << "This reference is generated from `spec.yaml` for OpenAPI #{spec.fetch('openapi')} contract review."
  lines << ''
  lines.join("\n")
end

unless ARGV.empty? || ARGV == ['--check']
  warn 'usage: scripts/generate-spec-md.rb [--check]'
  exit 64
end

spec_source = File.read(SPEC_PATH)
begin
  spec = YAML.safe_load(spec_source, aliases: true)
rescue SystemStackError
  warn 'spec.yaml exceeds the YAML generator parser nesting limit'
  exit 1
end
unless spec.is_a?(Hash)
  warn 'spec.yaml root must be a mapping for Markdown generation'
  exit 1
end

generated = generate_reference(spec)
if ARGV == ['--check']
  unless File.file?(REFERENCE_PATH) && File.read(REFERENCE_PATH) == generated
    warn 'spec.md is out of date; run scripts/generate-spec-md.rb'
    exit 1
  end
else
  File.write(REFERENCE_PATH, generated)
  puts 'Generated spec.md from spec.yaml.'
end
