#!/usr/bin/env sh
set -eu

ROOT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
WORK_DIR=$(mktemp -d "${TMPDIR:-/tmp}/poe-openapi-generator.XXXXXX")
trap 'rm -rf "$WORK_DIR"' EXIT HUP INT TERM

mkdir -p "$WORK_DIR/scripts"
cp "$ROOT_DIR/scripts/generate-spec-md.rb" "$WORK_DIR/scripts/"
cp "$ROOT_DIR/spec.yaml" "$ROOT_DIR/spec.md" "$WORK_DIR/"
chmod +x "$WORK_DIR/scripts/generate-spec-md.rb"

"$ROOT_DIR/scripts/generate-spec-md.rb" --check
cp "$ROOT_DIR/spec.yaml" "$WORK_DIR/spec.yaml"
cp "$WORK_DIR/spec.md" "$WORK_DIR/spec.md.before-recursion"
ruby - "$WORK_DIR/spec.yaml" <<'RUBY'
path = ARGV.fetch(0)
File.open(path, 'a') do |file|
  file.puts 'x-deep-acyclic:'
  1.upto(2_000) { |index| file.puts(('  ' * index) + "level#{index}:") }
  file.puts(('  ' * 2_001) + 'value: leaf')
end
RUBY
if output=$(ruby -rtimeout -e 'path = ARGV.shift; Timeout.timeout(5) { load path }' \
  "$WORK_DIR/scripts/generate-spec-md.rb" 2>&1); then
  printf '%s\n' 'generator accepted YAML beyond the parser nesting limit' >&2
  exit 1
fi
if [ "$output" != "spec.yaml exceeds the YAML generator parser nesting limit" ]; then
  printf '%s\n%s\n' 'generator returned the wrong parser recursion error:' "$output" >&2
  exit 1
fi
cmp "$WORK_DIR/spec.md.before-recursion" "$WORK_DIR/spec.md"
cp "$ROOT_DIR/spec.yaml" "$WORK_DIR/spec.yaml"
printf '%s\n' '<!-- drift -->' >> "$WORK_DIR/spec.md"
if output=$("$WORK_DIR/scripts/generate-spec-md.rb" --check 2>&1); then
  printf '%s\n' 'generator check accepted stale Markdown' >&2
  exit 1
fi
printf '%s\n' "$output" | grep -Fq 'spec.md is out of date; run scripts/generate-spec-md.rb'

"$WORK_DIR/scripts/generate-spec-md.rb" >/dev/null
"$WORK_DIR/scripts/generate-spec-md.rb" --check
for contract in \
  '<!-- Generated by scripts/generate-spec-md.rb from spec.yaml. Do not edit directly. -->' \
  '- **Endpoint**: `/stream-to-poe`' \
  '- **Operation ID**: `convertSseToPoe`' \
  '`sseUrl` (string, required)' \
  '- `404`: SSE stream not found' \
  '**`ApiKeyAuth`**' \
  '"details"'; do
  grep -Fq -- "$contract" "$WORK_DIR/spec.md"
done

cp "$ROOT_DIR/spec.yaml" "$WORK_DIR/spec.yaml"
ruby - "$WORK_DIR/spec.yaml" <<'RUBY'
require 'yaml'

path = ARGV.fetch(0)
spec = YAML.safe_load(File.read(path), aliases: true)
spec.fetch('info')['title'] = 'Mutation Contract'
spec.fetch('info')['version'] = '9.9.9'
spec.fetch('servers').first['description'] = 'Mutation server'
operation = spec.fetch('paths').fetch('/stream-to-poe').fetch('post')
operation['summary'] = 'Mutation operation summary'
operation['operationId'] = 'mutationOperation'
operation['description'] = 'Mutation operation description.'
operation.fetch('responses').fetch('404')['description'] = 'Mutation response description'
property = spec.fetch('components').fetch('schemas').fetch('SseConversionRequest').fetch('properties').fetch('contentType')
property['description'] = 'Mutation field description'
property['default'] = 'mutation/type'
security = spec.fetch('components').fetch('securitySchemes').fetch('ApiKeyAuth')
security['name'] = 'X-Mutation-Key'
security['description'] = 'Mutation security description.'
spec.fetch('components').fetch('schemas').fetch('Error').fetch('properties').fetch('message')['example'] = 'Mutation error example'
File.write(path, YAML.dump(spec))
RUBY
"$WORK_DIR/scripts/generate-spec-md.rb" >/dev/null
for mutation in \
  '# Mutation Contract API' \
  '- **Version**: 9.9.9' \
  '**Mutation server**' \
  '### 1. Mutation operation summary' \
  '- **Operation ID**: `mutationOperation`' \
  'Mutation operation description.' \
  'Mutation field description (default: `mutation/type`)' \
  '- `404`: Mutation response description' \
  'X-Mutation-Key' \
  'Mutation security description.' \
  'Mutation error example'; do
  grep -Fq -- "$mutation" "$WORK_DIR/spec.md"
done
"$WORK_DIR/scripts/generate-spec-md.rb" --check

if output=$("$WORK_DIR/scripts/generate-spec-md.rb" unexpected 2>&1); then
  printf '%s\n' 'generator accepted an unsupported argument' >&2
  exit 1
fi
printf '%s\n' "$output" | grep -Fq 'usage: scripts/generate-spec-md.rb [--check]'

printf '%s\n' 'Generated Markdown contract tests passed.'
